server:
   port: 8082
   servlet:
      context-path: /app-back
jwt:
   issuer: issuer
https-force: false

logging:
   level:
#      root: DEBUG
      org:
         springframework:
            web: DEBUG
spring:
   security:
      user:
         name: tinnova
         password: test
         roles: ADMIN
   datasource:
      url: jdbc:h2:file:./target/fst;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
      username: fst
      password: fst
      driverClassName: org.h2.Driver
   h2:
      console:
         enabled: true
   jpa:
      properties:
         hibernate:
            ddl-auto: create
            show_sql: false
            use_sql_comments: true
            format_sql: true
            temp:
               use_jdbc_metadata_defaults: false
            jdbc:
               time_zone: UTC
      database-platform: org.hibernate.dialect.H2Dialect
   liquibase:
      enabled: false
   main:
      allow-bean-definition-overriding: true